version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 3030:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    networks:
      - istiak2021
networks:
  istiak2021:
